language: php
dist: trusty
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  ## PHP_CodeSniffer
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then pear install pear/PHP_CodeSniffer; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then phpenv rehash; fi
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  ## - pear config-set preferred_state beta
  ## - printf "\n" | pecl install imagick
  ## - pear channel-discover pear.phpmd.org
  ## - pear channel-discover pear.pdepend.org
  ## - pear install --alldeps phpmd/PHP_PMD
  ## - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
  
script:
  ## PHP_CodeSniffer
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then phpcs --standard=PSR1 src/ -v; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then phpcs --standard=PSR2 src/ -v; fi
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose src/
  ## PHP Mess Detector
  ## - phpmd src/ text codesize,unusedcode,naming,design
  ## PHPLOC
  - php phploc.phar src/
  ## PHPUNIT
  - phpunit