language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  ## PHP_CodeSniffer
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
script:
  ## PHP_CodeSniffer
  - phpcs --standard=PSR1 ./*.php
  - phpcs --standard=PSR2 ./*.php